name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: List Python files
      run: find . -name "*.py" | xargs ls -la
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run linting (warning only)
      continue-on-error: true
      run: |
        pip install black flake8
        echo "Black formatting check:"
        black --check . || echo "⚠️ Black formatting issues found"
        echo "Flake8 style check:"
        flake8 . || echo "⚠️ Flake8 style issues found"